NAME = libft.a
SRCS = 	ft_atoi.c	 		\
		ft_bzero.c	 		\
		ft_count_int_tab.c	\
		ft_count_words.c	\
		ft_isalnum.c		\
		ft_isalpha.c		\
		ft_isascii.c		\
		ft_isdigit.c		\
		ft_isprint.c		\
		ft_itoa.c			\
		ft_memalloc.c		\
		ft_memccpy.c		\
		ft_memchr.c			\
		ft_memcmp.c			\
		ft_memcpy.c			\
		ft_memdel.c			\
		ft_memmove.c		\
		ft_memset.c			\
		ft_putchar.c		\
		ft_putchar_fd.c		\
		ft_putendl.c		\
		ft_putendl_fd.c		\
		ft_putnbr.c			\
		ft_putnbr_fd.c		\
		ft_putstr.c			\
		ft_putstr_fd.c		\
		ft_reverse_bits.c	\
		ft_splitwords.c		\
		ft_strcat.c			\
		ft_strchr.c			\
		ft_strclr.c			\
		ft_strcmp.c			\
		ft_strcpy.c			\
		ft_strdel.c			\
		ft_strdup.c			\
		ft_strequ.c			\
		ft_striter.c		\
		ft_striteri.c		\
		ft_strjoin.c		\
		ft_strlcat.c		\
		ft_strlen.c			\
		ft_strmap.c			\
		ft_strmapi.c		\
		ft_strncat.c		\
		ft_strncmp.c		\
		ft_strncpy.c		\
		ft_strnequ.c		\
		ft_strnew.c			\
		ft_strnstr.c		\
		ft_strrchr.c		\
		ft_strrev.c			\
		ft_strsplit.c		\
		ft_strstr.c			\
		ft_strsub.c			\
		ft_strtrim.c		\
		ft_tolower.c		\
		ft_toupper.c		\
		ft_intnew.c			\
		ft_sqrt.c			\
	   	ft_putnbr_hexa.c					\
	   	ft_count_size_hexa.c				\
	   	ft_putnbr_size_len.c				\
	   ft_putnbr_ssize_len.c			\
	   ft_count_size_number.c			\
	   ft_putnbr_len.c					\
	   ft_count_size_unsigned.c			\
	   ft_count_size_octal.c			\
	   ft_put_n_str.c					\
	   ft_put_n_char.c					\

OBJ = $(SRCS:.c=.o)
CC = gcc
OPTION = -c
FLAGS  = -Wall -Werror -Wextra

all: $(NAME)
	
$(NAME):
	@$(CC) $(FLAGS) $^  $(OPTION) $(SRCS)
	ar rc $(NAME) $(OBJ)
	ranlib $(NAME)
	@echo "\033[33;32m=== Compilation\t\t\tDONE"
	
clean:
	   @rm -f $(OBJ)
fclean: clean
	   @rm -f $(NAME)
	@echo "\033[33;12m=== fclean\t\t\tDONE"
re: fclean all
